services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: foobarpassword
      DB_NAME: arm_auth
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: foobarpassword
      REDIS_SESSION_TTL: 604800  

      JWT_ACCESS_SECRET: foobarnotsosecretkeychangeinproduction
      JWT_REFRESH_SECRET: foobarnotsosecretkeychangeinproductionREFRESH
      JWT_ACCESS_TTL: 15m
      JWT_REFRESH_TTL: 7d

      NODE_ENV: development
    env_file:
      - .env
 
  redis:
    image: redis:alpine
    restart: always
    command: >
      redis-server
      --appendonly yes
      --requirepass foobarpassword
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data 
    environment:
      REDIS_PASSWORD: foobarpassword
    depends_on:
      - db
    ports:
      - 6379:6379

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - db_data:/var/lib/postgresql


    environment:
      POSTGRES_PASSWORD: foobarpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: arm_auth
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# Volumes 
volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
